Sync the tox.ini files with the other plugins
Missed during the reviews process of the splitting. Main changes:

- envlist for py37 too;
- minversion bumped to 2.0;
- fixed the wrong basepython statement for for 'testenv' tox target;
- consider the expected dependencies in the 'pep8' and 'releasenotes'
  tox targets;
- add the 'lower-constraints' tox target

Exception: do not sync the ignore rules for pep8, as they
are apparently not needed.

Change-Id: I2297ed7b0b0fc1205feeff5686ec08439d7c814d